# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SpinSpeederIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpinSpeederIOS
  pod 'OpenCV', '~> 4.3.0'

end 